services:
  mongodb-primary:
    image: bitnami/mongodb:${MONGODB_VERSION}
    container_name: mongodb-primary
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=${MONGODB_DEFAULT_HOSTS:-}
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_PASSWORD=${MONGODB_DEFAULT_PASSWORDS:-}
      - MONGODB_REPLICA_SET_KEY=${MONGODB_DEFAULT_KEYS:-}
    ports:
      - 27017:27017
    volumes:
      - "./data:/bitnami"
    restart: unless-stopped

  mongodb-secondary:
    image: bitnami/mongodb:${MONGODB_VERSION}
    container_name: mongodb-secondary
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=${MONGODB_DEFAULT_HOSTS:-}
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_INITIAL_PRIMARY_HOST=mongodb-primary
      - MONGODB_INITIAL_PRIMARY_PORT_NUMBER=27017
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=${MONGODB_DEFAULT_PASSWORDS:-}
      - MONGODB_REPLICA_SET_KEY=${MONGODB_DEFAULT_KEYS:-}
    ports:
      - 27018:27017
    restart: unless-stopped

  mongodb-arbiter:
    image: bitnami/mongodb:${MONGODB_VERSION}
    container_name: mongodb-arbiter
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=${MONGODB_DEFAULT_HOSTS:-}
      - MONGODB_REPLICA_SET_MODE=arbiter
      - MONGODB_INITIAL_PRIMARY_HOST=mongodb-primary
      - MONGODB_INITIAL_PRIMARY_PORT_NUMBER=27017
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=${MONGODB_DEFAULT_PASSWORDS:-}
      - MONGODB_REPLICA_SET_KEY=${MONGODB_DEFAULT_KEYS:-}
    ports:
      - 27019:27017
    restart: unless-stopped